SERVERS_CONFIG_PATH = "/opt/supervision/data/servers.json"
FERNET_KEY_PATH = "/opt/supervision/secret.key"
ACCOUNTS_CONFIG_PATH = "/opt/supervision/data/accounts.json"
DATA_DIR = "/opt/supervision/data"
LOG_DIR = "/var/log/supervision"
